package com.DeskBooking.deskbooking.service;

import org.springframework.stereotype.Service;

@Service
public class HtmlData {
	
	public String confirmedRegistration() { //This should be done from file reader, lol, refactor this sh1t
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns:th=\"http://www.thymeleaf.org\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
				+ "    <head>\r\n"
				+ "    	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n"
				+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n"
				+ "        <title>v2</title>\r\n"
				+ "        <style>\r\n"
				+ "            @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');\r\n"
				+ "\r\n"
				+ "            * {\r\n"
				+ "                margin:0;\r\n"
				+ "                padding: 0;\r\n"
				+ "                border: 0;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            body {\r\n"
				+ "                font-family: 'Open Sans', sans-serif;\r\n"
				+ "                background-image: url(/images/backgroundImage.jpg);\r\n"
				+ " 				background-repeat: no-repeat;\r\n"
				+ "  				background-attachment: fixed;\r\n"
				+ "  				background-size: cover;\r\n"
				+ "                font-size: 24px;\r\n"
				+ "                max-width: 800px;\r\n"
				+ "                margin: 0 auto;\r\n"
				+ "                padding: 3%;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            .form{\r\n"
				+ "            	background-color: white;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            img {\r\n"
				+ "                max-width: 40%;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            header {\r\n"
				+ "                width: 98%;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "            #wrapper {\r\n"
				+ "                /* background-image: url('backgroundImage.jpg'); */\r\n"
				+ "                background-repeat: no-repeat;\r\n"
				+ "                background-attachment: fixed;\r\n"
				+ "                background-size: cover;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            #banner {\r\n"
				+ "                background-color: #fff;\r\n"
				+ "                text-align: center;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            h1,h3,p {\r\n"
				+ "                margin-top: 40px;\r\n"
				+ "                margin-bottom: 40px;\r\n"
				+ "                text-align: center;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            hr {\r\n"
				+ "                height: 1px;\r\n"
				+ "                background-color: black;\r\n"
				+ "                clear: both;\r\n"
				+ "                width: 90%;\r\n"
				+ "                margin: auto;\r\n"
				+ "            }\r\n"
				+ "            #contact {\r\n"
				+ "                text-align: center;\r\n"
				+ "                padding-bottom: 3%;\r\n"
				+ "                line-height: 15px;\r\n"
				+ "                font-size: 12px;\r\n"
				+ "                color: #303840;\r\n"
				+ "                margin: auto;\r\n"
				+ "            }\r\n"
				+ "            #one-col {\r\n"
				+ "                background-color: #FFF;\r\n"
				+ "            }\r\n"
				+ "            .footer {\r\n"
				+ "                background-color: #FFF;\r\n"
				+ "                margin-top: 15px;\r\n"
				+ "            }\r\n"
				+ "            .pbtn {\r\n"
				+ "                width: 100%;\r\n"
				+ "                display: flex;\r\n"
				+ "                justify-content: center;\r\n"
				+ "            }\r\n"
				+ "            .btn {\r\n"
				+ "                margin: auto;\r\n"
				+ "                background-color: #279CCE;\r\n"
				+ "                color: #FFF;\r\n"
				+ "                padding: 10px;\r\n"
				+ "                text-decoration: none;\r\n"
				+ "                font-weight: 800;\r\n"
				+ "                border-radius: 8px;\r\n"
				+ "                letter-spacing: 2px;\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "    </head>\r\n"
				+ "    <body>\r\n"
				+ "        <div id=\"wrapper\" class = \"form\">\r\n"
				+ "			<div class=\"one-col\">\r\n"
				+ "                  <h1>Successful registration!</h1>\r\n"
				+ "            </div>\r\n"
				+ "            <p>\r\n"
				+ "                Proceed to Login page\r\n"
				+ "            </p>\r\n"
				+ "            <div class=\"pbtn\">\r\n"
				+ "            	<a class=\"btn\" href = \"http://localhost:3000/login\">Login</a>\r\n"
				+ "            </div>  \r\n"
				+ "            <div class=\"footer\">\r\n"
				+ "                <p id=\"contact\">\r\n"
				+ "                 <img src=\"/images/deskbookIng1.png\" alt=\"\"/> <br /> \r\n"
				+ "                Copyright © 2021 enjoy.ing\r\n"
				+ "                </p>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </body>\r\n"
				+ "</html>";
	}
	public String resetPassword() {
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns:th=\"http://www.thymeleaf.org\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
				+ "    <head>\r\n"
				+ "    	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n"
				+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n"
				+ "        <title>v2</title>\r\n"
				+ "        <style>\r\n"
				+ "            @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');\r\n"
				+ "\r\n"
				+ "            * {\r\n"
				+ "                margin:0;\r\n"
				+ "                padding: 0;\r\n"
				+ "                border: 0;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            body {\r\n"
				+ "             	background-image: url(/images/backgroundImage.jpg);\r\n"
				+ "                font-family: 'Open Sans', sans-serif;\r\n"
				+ "                background-color: #fff;\r\n"
				+ "                font-size: 24px;\r\n"
				+ "                max-width: 800px;\r\n"
				+ "                margin: 0 auto;\r\n"
				+ "                padding: 3%;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            img {\r\n"
				+ "                max-width: 40%;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            header {\r\n"
				+ "                width: 98%;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "            #wrapper {\r\n"
				+ "                /* background-image: url('backgroundImage.jpg'); */\r\n"
				+ "                background-color: white;\r\n"
				+ "                background-repeat: no-repeat;\r\n"
				+ "                background-attachment: fixed;\r\n"
				+ "                background-size: cover;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            #banner {\r\n"
				+ "                background-color: #fff;\r\n"
				+ "                text-align: center;\r\n"
				+ "            }\r\n"
				+ "            \r\n"
				+ "            h1,h3,p,a {\r\n"
				+ "                margin-top: 40px;\r\n"
				+ "                margin-bottom: 40px;\r\n"
				+ "                text-align: center;\r\n"
				+ "            }\r\n"
				+ "            hr {\r\n"
				+ "                height: 1px;\r\n"
				+ "                background-color: black;\r\n"
				+ "                clear: both;\r\n"
				+ "                width: 90%;\r\n"
				+ "                margin: auto;\r\n"
				+ "            }\r\n"
				+ "            #contact {\r\n"
				+ "                text-align: center;\r\n"
				+ "                padding-bottom: 3%;\r\n"
				+ "                line-height: 15px;\r\n"
				+ "                font-size: 12px;\r\n"
				+ "                color: #303840;\r\n"
				+ "                margin: auto;\r\n"
				+ "            }\r\n"
				+ "            #one-col {\r\n"
				+ "                background-color: #FFF;\r\n"
				+ "            }\r\n"
				+ "            .footer {\r\n"
				+ "                background-color: #FFF;\r\n"
				+ "                margin-top: 15px;\r\n"
				+ "            }\r\n"
				+ "            .pbtn {\r\n"
				+ "                width: 100%;\r\n"
				+ "                display: flex;\r\n"
				+ "                justify-content: center;\r\n"
				+ "            }\r\n"
				+ "            .btn {\r\n"
				+ "                margin: auto;\r\n"
				+ "                background-color: #279CCE;\r\n"
				+ "                color: #FFF;\r\n"
				+ "                padding: 10px;\r\n"
				+ "                text-decoration: none;\r\n"
				+ "                font-weight: 800;\r\n"
				+ "                border-radius: 8px;\r\n"
				+ "                letter-spacing: 2px;\r\n"
				+ "                \r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "        </style>\r\n"
				+ "    </head>\r\n"
				+ "    <body>\r\n"
				+ "        <div id=\"wrapper\">\r\n"
				+ "\r\n"
				+ "            <div class=\"one-col\">\r\n"
				+ "                  <h1>Password successfully reset</h1>\r\n"
				+ "            </div>\r\n"
				+ "            <p>\r\n"
				+ "            Click the button below to Login with new password\r\n"
				+ "            </p>\r\n"
				+ "            <div class=\"pbtn\">\r\n"
				+ "            	<a href=\"http://localhost:3000/login\" class=\"btn\">Click to Login</a>\r\n"
				+ "            </div>\r\n"
				+ "            <p>If this isn't your request we advise you to contact enjoy.ing admin</p>\r\n"
				+ "            <hr />\r\n"
				+ "            <div class=\"footer\">\r\n"
				+ "                <p id=\"contact\">\r\n"
				+ "                 <img src=\"/images/deskbookIng1.png\" alt=\"\"/> <br /> \r\n"
				+ "                Copyright © 2021 enjoy.ing\r\n"
				+ "                </p>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </body>\r\n"
				+ "</html>";
		
	}
}
